### PR TITLE
Add Donjon to valid buildings

### PR DESCRIPTION
**Pull request by abductedPlatypus**

### CODE REVIEW

**Comment by happyleavesaoc** [comment]
Thanks. Had this added locally but haven't prepped for push yet.

**Comment by abductedPlatypus** [comment]
Thanks. It wrongfully marked Yo as a cheater in TP2 today.

**Comment by happyleavesaoc** [comment]
Honestly didn't think anyone was looking at that field besides me.

**Comment by abductedPlatypus** [comment]
I made a little tool to aid robo's admining work. Thought I'd check that
field as well.

**Pull request merged**
