### PR TITLE
Fix some python3 compile errors

### PR DESCRIPTION
**Pull request by nymanjens**

### CODE REVIEW

**Comment by happyleavesaoc** [comment]
Could we do `player_id, formation_id, *object_ids = ...` instead of `player_id, formation_id, (*object_ids,) = ...`?

**Comment by nymanjens** [comment]
Done

**Comment by happyleavesaoc** [comment]
Thanks!

**Comment by JacobALundgren** [comment]
Just to double-check, is there a particular reason why
https://github.com/happyleavesaoc/aoc-mgz/blob/master/mgz/fast/header.py#L108
was left in place? I seem to be getting the "can't use starred expression here" from this still, but maybe I'm just doing something wrong? Will gladly put in a PR for that otherwise!

**Comment by nymanjens** [comment]
I just fixed whatever needed to get it work on my machine.

**Pull request merged**
