### PR TITLE
Fix timeline for unit train

### PR DESCRIPTION
**Pull request by philipp94831**

### CODE REVIEW

**Comment by happyleavesaoc** [comment]
Thanks! Just pushed another commit, `_timeline` is now `_queue`, and it supports Wololo Kingdoms unit IDs.

**Comment by philipp94831** [comment]
@happyleavesaoc Do you have any clue how to assign queued units to a player? I only see the building_ids but cannot assign them to players...

**Comment by happyleavesaoc** [comment]
You can't. That information is not stored in the recorded game file.

**Comment by philipp94831** [comment]
That's sad. I wonder how the game handles this...

**Comment by happyleavesaoc** [comment]
It keeps a mapping of building ID to player ID.

**Comment by philipp94831** [comment]
Yeah, I thought so. Maybe I find a way to reconstruct these building_ids

**Comment by happyleavesaoc** [comment]
You won't be able to do it via the recorded game file. I had hoped there was a way to derive ownership, etc from the evidence in the file, but there doesn't seem to be a way.

**Comment by philipp94831** [comment]
okay

**Pull request merged**
