### PR TITLE
Change the zero const to a signed integer in the de/player struct

### PR DESCRIPTION
**Pull request by ZetaTwo**
In some replays, the value has been observed to be "-1" as opposed to "0"

The meaning of the value is still not known. A reference replay can be found in #106

### CODE REVIEW

**Comment by happyleavesaoc** [comment]
Can we not assume it means "AI"?

**Comment by ZetaTwo** [comment]
It is definitely related to AI players but I have replays with AI with this is still 0 so it's not simply whether it's an AI or not, we could name it something like "ai_unknown" for now.

**Comment by happyleavesaoc** [comment]
That works!

**Comment by ZetaTwo** [comment]
Done. This now "fixes" #106 in the sense that it successfully parses although the meaning is still now known.

**Pull request merged**
